#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# Set PATH
#
export PATH="/Users/pettereek/bin:/usr/local/go/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:./node_modules/.bin"

#
# syb-core tests
#
gtr() { go test -v -run="$1" }
jgtr() {
  TEST_REGEX=$1
  shift # shift all arguments so that $2 => $1 etc.
  TEST_FLAGS="$@" # Let TEST_FLAGS be rest of args

  TEST_FILE=$(fgrep -slr "$TEST_REGEX(" {auth,radio,payment}-lib/test geocoding | head -1)
  if [[ -n $TEST_FILE ]]; then
    go test -v "./$(dirname $TEST_FILE)/..." -test.run="$TEST_REGEX$" $TEST_FLAGS
  else
    echo "Did not find: $TEST_REGEX"
  fi
}

#
# syb helpers
#
jsyb() {
  syb $@ | jq
}

#
# Tyson helpers
#
TYSON_HOME="$HOME/Soundtrack/syb-custom/tyson"

player() {
  printcmd() {
    echo "🍄  $1\n"
    eval "$1"
  }

  printdone() {
    echo "🙏  $1 done"
  }

  case "$1" in
    "cd")
      printcmd "cd $TYSON_HOME"
      ;;
    "update")
      player cd
      printcmd "git pull --rebase"
      printcmd "cmake ."
      printcmd "make -j 4"
      printdone "$0 $1"
      ;;
    "start")
      player cd
      printcmd "./player-cli/player-cli --syb_file=cfg/petter-stage.json"
      printdone "$0 $1"
      ;;
    "cache-clean")
      player cd
      printcmd "rm -rf cache"
      printdone "$0 $1"
      ;;
    *)
      if [[ ! -z $1 ]] echo "$0: '$1' is not a command."
      echo "Usage: $0 cd|update|start|cache-clean"
  esac
}

#
# The next lines updates PATH for the Google Cloud SDK and enables shell command completion for gcloud.
#
gcloudPaths=(
/Users/pettereek/google-cloud-sdk/path.zsh.inc
/Users/pettereek/google-cloud-sdk/completion.zsh.inc
)
for p in "${gcloudPaths[@]}"; do
  if [ -f $p ]; then
    source $p
  fi
done

#
# nvm Node Version Manager
#
export NVM_DIR=~/.nvm
if [ -f $NVM_DIR/nvm.sh ]; then
  source $NVM_DIR/nvm.sh
fi

#
# Setup GOPATH, PATH for go
#
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"
export PATH="/usr/local/go_appengine:$PATH"

#
# The Fuck config
# https://github.com/nvbn/thefuck#installation
#
if type thefuck > /dev/null; then
  eval "$(thefuck --alias)"
  eval "$(thefuck --alias oops)"
  eval "$(thefuck --alias ooops)"
  eval "$(thefuck --alias oooops)"
  eval "$(thefuck --alias ooooops)"
fi

#
# Jump
# https://github.com/gsamokovarov/jump#installation
#
if type jump > /dev/null; then eval "$(jump shell zsh)"; fi

#
# swiftenv
# https://github.com/kylef/swiftenv/#installation
#
if type swiftenv > /dev/null; then eval "$(swiftenv init -)"; fi

#
# reminders-cli
#
alias rem=reminders

#
# kubectl
#
if type kubectl > /dev/null; then source <(kubectl completion zsh); fi
alias kc="kubectl"

#
# hibernation
#
alias sleepsafe='sudo pmset -a destroyfvkeyonstandby 1 hibernatemode 25'
alias sleepfast='sudo pmset -a hibernatemode 0'
alias sleepdefault='sudo pmset -a hibernatemode 3'

#
# conda
#
export PATH="$PATH:/Users/pettereek/miniconda2/bin"

#
# priv
#
source '/Users/pettereek/.zprezto/runcoms/zshrcpriv'
